In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('project_data3.csv')
data

지점  발생해역  발생유형   발생원인 기상상태   선 종  월별  시간대별      사고규모                일시  \
0      여수    영해    전복  운항부주의   양호  낚시어선  12     6  2.659574   2011-12-31 6:00   
1      부산   항계내    화재   정비불량   양호    어선  12    21  0.030538  2011-12-30 21:00   
2      속초    영해    침수   정비불량   양호    어선  12    11  0.333333  2011-12-30 11:00   
3      목포    영해    기타  운항부주의   양호   여객선  12    14  0.186235  2011-12-29 14:00   
4      목포    영해    기타   관리소홀   양호    기타  12    13  0.238095  2011-12-29 13:00   
...    ..   ...   ...    ...  ...   ...  ..   ...       ...               ...   
16967  울산  항계 내  기관손상   정비불량   양호  낚시어선   1    17  2.333333  2021-01-01 17:00   
16968  울산    영해  기관손상   정비불량   양호    어선   1    15  0.518135  2021-01-01 15:00   
16969  통영   협수로  기관손상   정비불량   양호  낚시어선   1    12  2.311248  2021-01-01 12:00   
16970  여수    영해    충돌  운항부주의   양호    어선   1    11  0.500000  2021-01-01 11:00   
16971  여수    영해    충돌  운항부주의   양호   여객선   1    11  0.235537  2021-01-01 11:00   

       풍속(m/s)  GUST풍속(m/s)  현지기압(hPa)  습도(%)  기온(°C)  최대파고(m)  파주기(sec)  
0          4.9          7.5     1027.9   51.0     4.8      1.1       6.4  
1          2.7          4.9     1028.6   58.0     8.6      2.2       6.4  
2          6.7          9.6     1030.0   51.0     5.1      2.8       4.3  
3          8.8         11.8     1028.4   64.0     4.7      2.5       6.4  
4          8.8         11.5     1029.4   63.0     4.8      3.1       6.4  
...        ...          ...        ...    ...     ...      ...       ...  
16967      7.0          9.7     1023.9   56.0     5.0      2.3       9.1  
16968      6.3          8.9     1023.9   55.0     4.4      3.0       8.0  
16969      8.0         10.3     1027.0   62.0     3.0      1.3       3.4  
16970      6.5          9.6     1027.9   59.0     4.5      1.7       7.1  
16971      6.5          9.6     1027.9   59.0     4.5      1.7       7.1  

[16972 rows x 17 columns]

# one_hot encoding을 적용하지 않아서 오류

In [11]:
from sklearn.model_selection import train_test_split
X_train_all, X_test, y_train_all, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [12]:
X_train, X_val, y_train, y_test = train_test_split(X_train_all, y_train_all, test_size = 0.25, random_state = 42)

In [13]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(random_state = 42)
classifier.fit(X_train, y_train)

ValueError: could not convert string to float: '인천'

### 추가적으로 사용하지 않을 발생원인, 일시 제거

In [15]:
data.drop(['발생원인', '일시'], axis=1, inplace=True)

In [16]:
data

지점  발생해역  발생유형 기상상태   선 종  월별  시간대별      사고규모  풍속(m/s)  GUST풍속(m/s)  \
0      여수    영해    전복   양호  낚시어선  12     6  2.659574      4.9          7.5   
1      부산   항계내    화재   양호    어선  12    21  0.030538      2.7          4.9   
2      속초    영해    침수   양호    어선  12    11  0.333333      6.7          9.6   
3      목포    영해    기타   양호   여객선  12    14  0.186235      8.8         11.8   
4      목포    영해    기타   양호    기타  12    13  0.238095      8.8         11.5   
...    ..   ...   ...  ...   ...  ..   ...       ...      ...          ...   
16967  울산  항계 내  기관손상   양호  낚시어선   1    17  2.333333      7.0          9.7   
16968  울산    영해  기관손상   양호    어선   1    15  0.518135      6.3          8.9   
16969  통영   협수로  기관손상   양호  낚시어선   1    12  2.311248      8.0         10.3   
16970  여수    영해    충돌   양호    어선   1    11  0.500000      6.5          9.6   
16971  여수    영해    충돌   양호   여객선   1    11  0.235537      6.5          9.6   

       현지기압(hPa)  습도(%)  기온(°C)  최대파고(m)  파주기(sec)  
0         1027.9   51.0     4.8      1.1       6.4  
1         1028.6   58.0     8.6      2.2       6.4  
2         1030.0   51.0     5.1      2.8       4.3  
3         1028.4   64.0     4.7      2.5       6.4  
4         1029.4   63.0     4.8      3.1       6.4  
...          ...    ...     ...      ...       ...  
16967     1023.9   56.0     5.0      2.3       9.1  
16968     1023.9   55.0     4.4      3.0       8.0  
16969     1027.0   62.0     3.0      1.3       3.4  
16970     1027.9   59.0     4.5      1.7       7.1  
16971     1027.9   59.0     4.5      1.7       7.1  

[16972 rows x 15 columns]

## 범주형 데이터 one-hotencoding

In [18]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
ohe.fit(data[['지점']])
print(ohe.transform(data[['지점']]))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [19]:
ohe.categories_

[array(['목포', '보령', '부산', '서귀포', '속초', '여수', '완도', '울산', '울진', '인천', '제주',
        '태안', '통영', '평택', '포항'], dtype=object)]

In [21]:
data_loc = pd.DataFrame(ohe.transform(data[['지점']]), columns=['목포', '보령', '부산', '서귀포', '속초', '여수', '완도', '울산', '울진', '인천', '제주',
        '태안', '통영', '평택', '포항'])
data_loc

목포   보령   부산  서귀포   속초   여수   완도   울산   울진   인천   제주   태안   통영   평택  \
0      0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1      0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2      0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3      1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4      1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
16967  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
16968  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
16969  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
16970  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
16971  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

        포항  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0  
...    ...  
16967  0.0  
16968  0.0  
16969  0.0  
16970  0.0  
16971  0.0  

[16972 rows x 15 columns]

### 한꺼번에 수행하고자 get_dummies 라는 함수 사용

In [24]:
dummy = pd.get_dummies(data, columns = ['지점','발생해역', '기상상태', '선 종'])

### 그렇게 생성한 data와 dummy들을 합치기

In [25]:
df = pd.concat([data,dummy],axis=1)
df

지점  발생해역  발생유형 기상상태   선 종  월별  시간대별      사고규모  풍속(m/s)  GUST풍속(m/s)  \
0      여수    영해    전복   양호  낚시어선  12     6  2.659574      4.9          7.5   
1      부산   항계내    화재   양호    어선  12    21  0.030538      2.7          4.9   
2      속초    영해    침수   양호    어선  12    11  0.333333      6.7          9.6   
3      목포    영해    기타   양호   여객선  12    14  0.186235      8.8         11.8   
4      목포    영해    기타   양호    기타  12    13  0.238095      8.8         11.5   
...    ..   ...   ...  ...   ...  ..   ...       ...      ...          ...   
16967  울산  항계 내  기관손상   양호  낚시어선   1    17  2.333333      7.0          9.7   
16968  울산    영해  기관손상   양호    어선   1    15  0.518135      6.3          8.9   
16969  통영   협수로  기관손상   양호  낚시어선   1    12  2.311248      8.0         10.3   
16970  여수    영해    충돌   양호    어선   1    11  0.500000      6.5          9.6   
16971  여수    영해    충돌   양호   여객선   1    11  0.235537      6.5          9.6   

       ...  선 종_기타(통선)  선 종_낚시어선  선 종_모터보트  선 종_어선  선 종_여객선 선 종_예부선  선 종_요트  \
0      ...           0         1         0       0        0       0       0   
1      ...           0         0         0       1        0       0       0   
2      ...           0         0         0       1        0       0       0   
3      ...           0         0         0       0        1       0       0   
4      ...           0         0         0       0        0       0       0   
...    ...         ...       ...       ...     ...      ...     ...     ...   
16967  ...           0         1         0       0        0       0       0   
16968  ...           0         0         0       1        0       0       0   
16969  ...           0         1         0       0        0       0       0   
16970  ...           0         0         0       1        0       0       0   
16971  ...           0         0         0       0        1       0       0   

       선 종_유도선  선 종_유조선  선 종_화물선  
0            0        0        0  
1            0        0        0  
2            0        0        0  
3            0        0        0  
4            0        0        0  
...        ...      ...      ...  
16967        0        0        0  
16968        0        0        0  
16969        0        0        0  
16970        0        0        0  
16971        0        0        0  

[16972 rows x 73 columns]

In [27]:
df.drop(['지점', '발생해역', '선 종', '기상상태'], axis=1, inplace=True)

In [28]:
df

발생유형  월별  시간대별      사고규모  풍속(m/s)  GUST풍속(m/s)  현지기압(hPa)  습도(%)  \
0        전복  12     6  2.659574      4.9          7.5     1027.9   51.0   
1        화재  12    21  0.030538      2.7          4.9     1028.6   58.0   
2        침수  12    11  0.333333      6.7          9.6     1030.0   51.0   
3        기타  12    14  0.186235      8.8         11.8     1028.4   64.0   
4        기타  12    13  0.238095      8.8         11.5     1029.4   63.0   
...     ...  ..   ...       ...      ...          ...        ...    ...   
16967  기관손상   1    17  2.333333      7.0          9.7     1023.9   56.0   
16968  기관손상   1    15  0.518135      6.3          8.9     1023.9   55.0   
16969  기관손상   1    12  2.311248      8.0         10.3     1027.0   62.0   
16970    충돌   1    11  0.500000      6.5          9.6     1027.9   59.0   
16971    충돌   1    11  0.235537      6.5          9.6     1027.9   59.0   

       기온(°C)  최대파고(m)  ...  선 종_기타(통선) 선 종_낚시어선  선 종_모터보트  선 종_어선  선 종_여객선  \
0         4.8      1.1  ...           0        1         0       0        0   
1         8.6      2.2  ...           0        0         0       1        0   
2         5.1      2.8  ...           0        0         0       1        0   
3         4.7      2.5  ...           0        0         0       0        1   
4         4.8      3.1  ...           0        0         0       0        0   
...       ...      ...  ...         ...      ...       ...     ...      ...   
16967     5.0      2.3  ...           0        1         0       0        0   
16968     4.4      3.0  ...           0        0         0       1        0   
16969     3.0      1.3  ...           0        1         0       0        0   
16970     4.5      1.7  ...           0        0         0       1        0   
16971     4.5      1.7  ...           0        0         0       0        1   

       선 종_예부선  선 종_요트  선 종_유도선  선 종_유조선  선 종_화물선  
0            0       0        0        0        0  
1            0       0        0        0        0  
2            0       0        0        0        0  
3            0       0        0        0        0  
4            0       0        0        0        0  
...        ...     ...      ...      ...      ...  
16967        0       0        0        0        0  
16968        0       0        0        0        0  
16969        0       0        0        0        0  
16970        0       0        0        0        0  
16971        0       0        0        0        0  

[16972 rows x 69 columns]

In [36]:
df.isnull().sum()

발생유형         0
월별           0
시간대별         0
사고규모       125
풍속(m/s)      0
          ... 
선 종_예부선      0
선 종_요트       0
선 종_유도선      0
선 종_유조선      0
선 종_화물선      0
Length: 69, dtype: int64

In [37]:
df = df.dropna()

In [38]:
df.isnull().sum()

발생유형       0
월별         0
시간대별       0
사고규모       0
풍속(m/s)    0
          ..
선 종_예부선    0
선 종_요트     0
선 종_유도선    0
선 종_유조선    0
선 종_화물선    0
Length: 69, dtype: int64

In [42]:
df.to_csv('project_data4.csv',index=False, encoding='utf-8-sig')